# -*- encoding: utf-8 -*-

major_general = (''
    'I am the very model of a modern Major-General{enz}'
    'I\'ve information vegetable; animal; and mineral{enz}'
    'I know the kings of England; and I quote the fights historical{enz}'
    'From Marathon to Waterloo; in order categorical{enz}'
    'I\'m very well acquainted; too; with matters mathematical{enz}'
    'I understand equations both the simple and quadratical{enz}'
    'About binomial theorem I\'m teeming with a lot o\' news (bothered for a rhyme){enz}'
    'With many cheerful facts about the square of the hypotenuse{enz}'
    ''
    'I\'m very good at integral and differential calculus{enz}'
    'I know the scientific names of beings animalculous{enz}'
    'In short; in matters vegetable; animal; and mineral{enz}'
    'I am the very model of a modern Major-General{enz}'
    ''
    'I know our mythic history; King Arthur\'s and Sir Caradoc\'s{enz}'
    'I answer hard acrostics; I\'ve a pretty taste for paradox{enz}'
    'I quote in elegiacs all the crimes of Heliogabalus{enz}'
    'In conics I can floor peculiarities parabolous{enz}'
    'I can tell undoubted Raphaels from Gerard Dows and Zoffanies{enz}'
    'I know the croaking chorus from The Frogs of Aristophanes!{enz}'
    'Then I can hum a fugue of which I\'ve heard the music\'s din afore; (bothered for a rhyme){enz}'
    'And whistle all the airs from that infernal nonsense Pinafore{enz}'
    '')
